# Generated by Django 3.2 on 2023-02-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
